[python]
requirements = [
    "streamlit",
    "ultralytics==8.0.196",
    "opencv-python-headless==4.8.1.78",
    "torch",
    "torchvision",
    "Pillow",
    "numpy",
    "PyYAML"
]

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[browser]
gatherUsageStats = false
